siteTitle = 'Tủ lạnh Store3'
siteDescr = 'Refrigerator Store3'
siteDescription = "Đồ nội địa Nhật Bản đặc biệt là Tủ Lạnh tốt và bền"
siteUrl = "https://appstore3.info"
siteBandcampUrl = 'https://appstore3.info'
siteAddress = 'Tổ 03, Khu phố Bà Tri, Phường Tân Hiệp, Thị xã Tân Uyên, Bình Dương'
siteAddress2 = '090 268 3189 - Đoàn Bình'
siteSoundcloudUrl = 'https://soundcloud.com/sentimony'
siteFacebookUrl = 'https://www.facebook.com/phuquoctrasua'
siteDiscogsUrl = 'https://www.discogs.com/label/82598-Sentimony-Records'
siteTwitterUrl = 'https://twitter.com/nihon_ne'
siteGoogleplusUrl = ''
siteGithubUrl = 'https://github.com/nihonne'
siteYoutubeUrl = 'https://www.youtube.com/channel/UC2xhVmkOYPKibhJm3f0f3hw'

linkPrefix = '/'
